Season5/down in the river to pray
Jim-Duke/concordia-sacrae pull request #12
Opened 2021-01-17 23:15 UTC by nocollier

This work is ready for comment, I have checked each part and listened to several midi files. 

To make the merge a little easier I did not yet change the makefile, I figured we can change that in your PR.

Feel free to be picky, I tried to mostly stick with you style but it is my first attemp.

2021-01-19 23:26 UTC, Jim-Duke commented
- Williard should be Willard.
- There is a separate "arranger" variable; so Brock Willard can be assigned to that
- I like using bar markers - they aren't technically needed; but they do help check to see if you misaligned things or put the wrong duration on a note.
- I like to force line breaks to make the systems on our output match the systems on the original music.  I find that makes it easier to do a visual inspection.
- The original music has the Tenor lines on the "treble 8" clef (one octave lower than the normal treble clef).  So all the tenor lines are an octave too high.  Easily fixed.  Just add a "\clef "treble_8"" line.  And start the music phrase with one less apostrophe.

Still listening and examining notes.  So far all looks correct.  But I'll post this comment before finishing that.

Comments on the arrangement
- It seems strange.  I suppose I could get used to it.  I wonder if Scott realizes it.
- They just put it down in the key of "C", even though the music is in the key of B.

2021-01-19 23:42 UTC, Jim-Duke requested changes

2021-01-19 23:42 UTC, Jim-Duke commented on season_5/down_in_the_river_to_pray.ly
> +  composer = "George H. Allan, Brock Williard"
Williard should be Willard

2021-01-19 23:42 UTC, Jim-Duke commented on season_5/down_in_the_river_to_pray.ly
> +  r1 r1 r1 r1 r1 r1 r1 r1 r1
This is optional; but I like putting bar checks in the music.  It catches lots of errors; at least it does for me (wrong duration, skipped a note, forgot a change in time signature, etc.).

Also, for one of the voices I like to add forced line breaks (and stop linebreaks) by adding "\noBreak", and "\break" respectively as needed to force our systems to match the systems in the original music.  I find that it's much easier to make a visual inspection of notes that way.

2021-01-19 23:42 UTC, Jim-Duke commented on season_5/down_in_the_river_to_pray.ly
> +  \key c \major
The music has the Tenors using a tenor cleff (a G clef with an 8 under it).  In lilypond you can specify that with "\clef "treble_8"".  As a result, of this mistake, the tenor notes are all one octave too high.  That's easily corrected by deleting one of the apostrophe's from the relative starting pitch.

2021-01-20 02:08 UTC, Jim-Duke requested changes

2021-01-20 02:08 UTC, Jim-Duke commented on season_5/down_in_the_river_to_pray.ly
> +  a4 g4 fis4( fis8) b8
The 1/8th note B at the end of the measure before the 3/2 needs to go down.  The nearest B is up; so you need to add a comma.  And the F-sharp in the next measure will then need to be forced up with an apostrophe.  Same will hold for the Bass II part, of course.

2021-01-20 02:08 UTC, Jim-Duke commented on season_5/down_in_the_river_to_pray.ly
> +  gis4 fis4 gis4~ gis8 gis8
Almost missed this.  The dashed slurs/ties - I don't think they're actually slurs or ties.  I think they mean something like don't take a breath or something.  In this case (Alto voice, Page 7, system 2, last measure) - look at the words.  You can't tie the g# quarter note with the g# eighth note - you need to articulate two different words with those notes.  If we tie them, the rhythm in the MIDI won't match what's needed.  I think for creating MIDI's we should omit all dashed slurs.  Most of the time it's a slur and the rhythms will come out in the MIDI.  But in several places it changes the rhythm.  I won't identify more of those - scan through the music to find them and remove them.

2021-01-20 15:10 UTC, Jim-Duke commented
Also, during this review I again realized how much I depend on measure numbers to review the music efficiently and make corrections.  And that includes noting the measure number in comments in the source file.  I went ahead and made all the corrections I noted in my review.  Then I'm going to commit the changes and add this song to makefile and push the tracks up to the shared drive; and get others to give it a listen.

2021-01-20 15:26 UTC, nocollier commented
This arrangement is weird. With that many consistent sharps, I knew it must have not really been in C. This is a trend I have seen in orchestral work as well--it is written in some key, but you don't get to know up front what it is.
 
I don't really care for the arrangement either, but as you say I could probably get used to it. From my view, this is a simple song that sounds best simple, but the arrangement likes to add additional moods and moving lines in strange places. We will see how it goes.

I made the changes you suggested before I saw your last comment, feel free to what is easiest. If you like what you have we can even reject this PR and you can just push what you have. I will use all your suggestions from the beginning on the next one.

2021-01-20 15:30 UTC, Jim-Duke commented
If needed I can make commits to your branch.  No reason to reject the PR.  The vast majority of the file is correct.  The hard part - the notes and rhythms.  With a few exceptions that I noted.  I'll look over your changes and I think we can commit this.  If you could look over my PR we can push these forward.  I'll work on Ezekiel, since I have the sheet music.  You keep working on digital content.  There are two more scores available to work on.  I'll be getting the first shipment of sheet music this Friday - and I'll make scans so we can keep working things.

2021-01-20 17:56 UTC, nocollier commented
Ok, I will try to get to review your score tonight or maybe tomorrow. Thanks!

2021-01-21 01:22 UTC, Jim-Duke approved these changes

2021-01-21 01:23 UTC, merged